import SwiftUI

enum AppIcons: String, CaseIterable {
    case underline = "\u{e800}"
    case alignLeft = "\u{e801}"
    case grid = "\u{e802}"
    case search = "\u{e803}"
    case verifiedOk = "\u{e804}"
    case tick24 = "\u{e805}"
    case arrowLeft = "\u{e806}"
    case bold = "\u{e807}"
    case info = "\u{e808}"
    case add = "\u{e809}"
    case sorting = "\u{e80a}"
    case copyClone = "\u{e80b}"
    case setting = "\u{e80c}"
    case clearAll = "\u{e80d}"
    case contextMenuIcon = "\u{e80e}"
    case clock = "\u{e80f}"
    case eye = "\u{e810}"
    case delete = "\u{e811}"
    case exitFullScreen = "\u{e812}"
    case alignCenter = "\u{e813}"
    case user = "\u{e814}"
    case filter = "\u{e815}"
    case close = "\u{e816}"
    case globe = "\u{e817}"
    case backArrow = "\u{e818}"
    case category = "\u{e819}"
    case automation = "\u{e81a}"
    case image = "\u{e81b}"
    case agentPortal = "\u{e81c}"
    case error = "\u{e81d}"
    case fieldForms = "\u{e81e}"
    case arrowRight = "\u{e81f}"
    case orderedList = "\u{e820}"
    case sla = "\u{e821}"
    case groups = "\u{e822}"
    case reports = "\u{e823}"
    case chevronRight = "\u{e824}"
    case link1 = "\u{e825}"
    case chart = "\u{e826}"
    case filterActive = "\u{e827}"
    case more = "\u{e828}"
    case agents = "\u{e829}"
    case link = "\u{e82a}"
    case arrowUp = "\u{e82b}"
    case kb = "\u{e82c}"
    case extendExpiry = "\u{e82d}"
    case chevronDown = "\u{e82e}"
    case tag = "\u{e82f}"
    case reply = "\u{e830}"
    case alignRight = "\u{e831}"
    case profile = "\u{e832}"
    case sorting1 = "\u{e833}"
    case fullScreen = "\u{e834}"
    case italic = "\u{e835}"
    case permissions1 = "\u{e836}"
    case dashboard = "\u{e837}"
    case edit = "\u{e838}"
    case insertCode = "\u{e839}"
    case circleClose = "\u{e83a}"
    case mail = "\u{e83b}"
    case filterClear = "\u{e83c}"
    case fullpage = "\u{e83d}"
    case notifications = "\u{e83e}"
    case unorderedList = "\u{e83f}"
    case chevronUp = "\u{e840}"
    case chevronLeft = "\u{e841}"
    case permission = "\u{e842}"
    case background = "\u{e843}"
    case fillStar = "\u{e844}"
    case history = "\u{e845}"
    case lock = "\u{e846}"
    case star = "\u{e847}"
    case notes = "\u{e848}"
    case font = "\u{e849}"
    case strikethrough = "\u{e84a}"
    case arrowDown = "\u{e84b}"
    case cannedResponse = "\u{e84c}"
    case customerPortal = "\u{e84d}"
    case reset = "\u{e84e}"
    case emailNotification = "\u{e84f}"
    case key = "\u{e850}"
    case workSchedule = "\u{e851}"
    case brands = "\u{e852}"
    case ticket = "\u{e853}"
    case sort = "\u{e854}"
    case tick16 = "\u{e855}"
    case low = "\u{e856}"
    case delete1 = "\u{e857}"
    case website = "\u{e858}"
    case contactPhone = "\u{e859}"
    case normal = "\u{e85a}"
    case high = "\u{e85b}"
    case help = "\u{e85c}"
    case ticketNew = "\u{e85d}"
    case critical = "\u{e85e}"
    case date = "\u{e85f}"
    case dropdownMultiselect = "\u{e860}"
    case dropdownSingleselect = "\u{e861}"
    case regex = "\u{e862}"
    case checkbox = "\u{e863}"
    case textboxSingleline = "\u{e864}"
    case decimal = "\u{e865}"
    case yesNo = "\u{e866}"
    case url = "\u{e867}"
    case datetime = "\u{e868}"
    case textboxMultiline = "\u{e869}"
    case numeric = "\u{e86a}"
    case urlPrefix = "\u{e86b}"
    case spam = "\u{e86c}"
    case edit1 = "\u{e86d}"
    case replyLine = "\u{e86e}"
    case privateNote = "\u{e86f}"
    case worklog = "\u{e870}"
    case privateNoteFill = "\u{e871}"
    case unblock = "\u{e872}"
    case replyFill = "\u{e873}"
    case columnChooser = "\u{e874}"
    case refresh = "\u{e875}"
    case webhook = "\u{e876}"
    case removeSpam = "\u{e877}"
    case spam1 = "\u{e878}"
    case split = "\u{e879}"
    case expand = "\u{e87a}"
    case collapse1 = "\u{e87b}"
    case addWorklog = "\u{e87c}"
    case restore = "\u{e87d}"
    case collapse = "\u{e87e}"
    case expand1 = "\u{e87f}"
    case contactGroups = "\u{e880}"
    case priority = "\u{e881}"
    case status = "\u{e882}"
    case displayName = "\u{e883}"
    case language = "\u{e884}"
    case address = "\u{e885}"
    case description = "\u{e886}"
    case mobile = "\u{e887}"
    case type = "\u{e888}"
    case jobTitle = "\u{e889}"
    case subject = "\u{e88a}"
    case hide = "\u{e88b}"
    case subjectFill = "\u{e88c}"
    case contactAccessScope = "\u{e88d}"
    case timeZone = "\u{e88e}"
    case feedback = "\u{e88f}"
    case privatenoteNew = "\u{e890}"
    case deleteForever = "\u{e891}"
    case removeSpamNew = "\u{e892}"
    case replyLeft = "\u{e893}"
    case worklogNew = "\u{e894}"
    case xlsx = "\u{e895}"
    case sevenZ = "\u{e896}"
    case zipx = "\u{e897}"
    case doc = "\u{e898}"
    case jpg = "\u{e899}"
    case xls = "\u{e89a}"
    case rar = "\u{e89b}"
    case zip = "\u{e89c}"
    case csv = "\u{e89d}"
    case otherFiles = "\u{e89e}"
    case pdf = "\u{e89f}"
    case zip1 = "\u{e8a0}"
    case svg = "\u{e8a1}"
    case png = "\u{e8a2}"
    case spamNew = "\u{e8a3}"
    case apiDocs = "\u{e8a4}"
    case tutorialVideos = "\u{e8a5}"
    case keyboardShortcuts = "\u{e8a6}"
    case impersonate = "\u{e8a7}"
    case convertToAgent = "\u{e8a8}"
    case weblinks = "\u{e8a9}"
    case whatsnew = "\u{e8aa}"
    case myApps = "\u{e8ab}"
    case ascending = "\u{e8ac}"
    case descending = "\u{e8ad}"
    case frontArrow = "\u{e8ae}"
    case marketPlace = "\u{e8af}"
    case moveToTop = "\u{e8b0}"
    case moveToBottom = "\u{e8b1}"
    case activateBrand = "\u{e8b2}"
    case activateCustomerPortal = "\u{e8b3}"
    case deactivateCustomerPortal = "\u{e8b4}"
    case deactivateBrand = "\u{e8b5}"
    case home = "\u{e8b6}"
    case export = "\u{e8b7}"
    case arrowUpFill = "\u{e8b8}"
    case satisfactionSurvey = "\u{e8b9}"
    case editSubdomain = "\u{e8ba}"
    case editBrand = "\u{e8bb}"
    case setAsDefault = "\u{e8bc}"
    case editSetting = "\u{e8bd}"
    case editFilter = "\u{e8be}"
    case removeDefault = "\u{e8bf}"
    case bookmarkOutline = "\u{e8c0}"
    case bookmarkFill = "\u{e8c1}"
    case homeAgent = "\u{e8c2}"
    case noNeed = "\u{e8c3}"
    case billingSubscription = "\u{e8c4}"
    case invoice = "\u{e8c5}"
    case payment = "\u{e8c6}"
    case uninstall = "\u{e8c7}"
    case enableTicketCreation = "\u{e8c8}"
    case disableTicketCreation = "\u{e8c9}"
    case view = "\u{e8ca}"
    case viewProfile = "\u{e8cb}"
    case knowledgeBase = "\u{e8cc}"
    case insertLink = "\u{e8cd}"
    case line = "\u{e8ce}"
    case quotes = "\u{e8cf}"
    case table = "\u{e8d0}"
    case uploadFile = "\u{e8d1}"
    case insertVideo = "\u{e8d2}"
    case codeBlock = "\u{e8d3}"
    case header = "\u{e8d4}"
    case file = "\u{e8d5}"
    case fileText = "\u{e8d6}"
    case flag = "\u{e8d7}"
    case folder = "\u{e8d8}"
    case inbox = "\u{e8d9}"
    case layout = "\u{e8da}"
    case monitor = "\u{e8db}"
    case pieChart = "\u{e8dc}"
    case shield = "\u{e8dd}"
    case shoppingBag = "\u{e8de}"
    case archive = "\u{e8df}"
    case box = "\u{e8e0}"
    case database = "\u{e8e1}"
    case categoryKb = "\u{e8e2}"
    case selection = "\u{e8e3}"
    case infoBox = "\u{e8e4}"
    case warningBox = "\u{e8e5}"
    case errorBox = "\u{e8e6}"
    case share = "\u{e8e7}"
    case setAsDefault1 = "\u{e8e8}"
    case viewSettings = "\u{e8e9}"
    case billingSubscription1 = "\u{e8ea}"
    case dislike = "\u{e8eb}"
    case feedbackForm = "\u{e8ec}"
    case like = "\u{e8ed}"
    case widget = "\u{e8ee}"
    case api = "\u{e8ef}"
    case webForm = "\u{e8f0}"
    case message = "\u{e8f1}"
    case play = "\u{e8f2}"
    case pocket = "\u{e8f3}"
    case send = "\u{e8f4}"
    case server = "\u{e8f5}"
    case tool = "\u{e8f6}"
    case useThisTemplate = "\u{e8f7}"
    case homeKb = "\u{e8f8}"
    case squarePlus = "\u{e8f9}"
    case move = "\u{e8fa}"
    case moveKb = "\u{e8fb}"
    case warning = "\u{e8fc}"
    case errorKb = "\u{e8fd}"
    case `private` = "\u{e8fe}"
    case articleFill = "\u{e8ff}"
    case categoryFill = "\u{e900}"
    case folderOpen = "\u{e901}"
    case merge = "\u{e902}"
    case printer = "\u{e903}"
    case folderNew = "\u{e904}"
    case articleNew = "\u{e905}"
    case convert = "\u{e906}"
    case useTemplate = "\u{e907}"
    case template = "\u{e908}"
    case showEmail = "\u{e909}"
    case emailDeliveryStatus = "\u{e90a}"
    case excel = "\u{e90b}"
    case learningCenter = "\u{e90c}"
    case verified = "\u{e90d}"
    case unverified = "\u{e90e}"
    case verifiedFill = "\u{e90f}"
    case addApprover = "\u{e910}"
    case meeting = "\u{e911}"
    case task = "\u{e912}"
    case call = "\u{e913}"
    case activity = "\u{e914}"
    case approval = "\u{e915}"
    case pending = "\u{e916}"
    case articleNew1 = "\u{e917}"
    case skip = "\u{e918}"
    case copy = "\u{e919}"
    case rephrase = "\u{e91a}"
    case mobileApp = "\u{e91b}"
    case expandText = "\u{e91c}"
    case grammarCheck = "\u{e91d}"
    case viewSummary = "\u{e91e}"
    case shorten = "\u{e91f}"
    case ai = "\u{e920}"
    case forwardTicket = "\u{e921}"
    case translate = "\u{e922}"
    case remainderSent = "\u{e923}"
    case remainder = "\u{e924}"
    case mailNotSend = "\u{e925}"
    case agentReply = "\u{e926}"
    case fileSignature = "\u{e927}"
    case circle = "\u{e928}"
    case chat = "\u{e929}"
    case sendHorizontal = "\u{e92a}"
    case smile = "\u{e92b}"
    case importData = "\u{e92c}"
    case customStatus = "\u{e92d}"
    case quarantined = "\u{e92e}"
    case queueYetToScan = "\u{e92f}"
    case restored = "\u{e930}"
    case safe = "\u{e931}"
    case fileScan1 = "\u{e932}"
    case bookOpenRead1 = "\u{e933}"
    case whatsapp2 = "\u{e934}"
    case contactFields = "\u{e935}"
    case contactGroupFields = "\u{e936}"
    case createTrigger = "\u{e937}"
    case fieldDependency = "\u{e938}"
    case holidayList = "\u{e939}"
    case ticketFields = "\u{e93a}"
    case ticketForms = "\u{e93b}"
    case timeTrigger = "\u{e93c}"
    case updateTrigger = "\u{e93d}"
    case visitorFields = "\u{e93e}"
    case activityFields = "\u{e93f}"
    case cannedChatResponse = "\u{e940}"
    case chatAutomation = "\u{e941}"
    case chatFields = "\u{e942}"
    case chatForms = "\u{e943}"
    case chatSla = "\u{e944}"
    case chatTags = "\u{e945}"
    case chatViews = "\u{e946}"
    case chat2 = "\u{e947}"
    case slack = "\u{e948}"
    case teams = "\u{e949}"
    case zapier = "\u{e94a}"
    case doubleTick = "\u{e94b}"
    case messageStatus = "\u{e94c}"
    case moon = "\u{e94d}"
    case sun = "\u{e94e}"
    case kbOpen = "\u{e94f}"
    case facebook = "\u{e950}"
    case arrowLeftDown = "\u{e951}"
    case historyAlt = "\u{e952}"
    case attachment = "\u{e953}"
    case heading1 = "\u{e954}"
    case heading2 = "\u{e955}"
    case heading3 = "\u{e956}"
    case heading4 = "\u{e957}"
    case heading5 = "\u{e958}"
    case heading6 = "\u{e959}"
    case pilcrow = "\u{e95a}"
    case exotel = "\u{e95b}"
    case agentLoad = "\u{e95c}"
    case agentShift = "\u{e95d}"
    case cornerDownLeft = "\u{e95e}"
    case facebook1 = "\u{e95f}"
    case visitors = "\u{e960}"
    case whatsappTemplate = "\u{e961}"
    case ringover = "\u{e962}"
    case slackFilled = "\u{e963}"
    case redirectionRule = "\u{e964}"
    case filter1 = "\u{e965}"
    case instagram = "\u{e966}"
    case masterView = "\u{e967}"
    case schedule = "\u{e968}"
    case uploadCloud = "\u{e969}"
    case chatFill = "\u{e96a}"
    case codeView = "\u{e96b}"
    case downloadCloud = "\u{e96c}"
    case liquid = "\u{e96d}"
    case aArrowDown = "\u{e96e}"
    case brush = "\u{e96f}"
    case filterLines = "\u{e970}"
    case image03 = "\u{e971}"
    case divider = "\u{e972}"
    case articleAi = "\u{e973}"
    case aiIcon = "\u{e974}"
    case more1 = "\u{e975}"
    case quickStart = "\u{e976}"
    case customize = "\u{e977}"
    case automation1 = "\u{e978}"
    case productivity = "\u{e979}"
    case additionalFeatures = "\u{e97a}"
    case ticketTemplate = "\u{e97b}"
    case schedulerAdd = "\u{e97c}"
    case playFill = "\u{e97d}"
    case assignee = "\u{e97e}"
    case review = "\u{e97f}"
    case download = "\u{e980}"
    case aiAssist = "\u{e981}"
    case export1 = "\u{e982}"
    case airCall = "\u{e983}"
    case received1 = "\u{e984}"
    case send1 = "\u{e985}"
    case received2 = "\u{e986}"
    case send2 = "\u{e987}"
    case home2 = "\u{e988}"
    case unassigned = "\u{e989}"
    case security = "\u{e98a}"
    case circleAdd = "\u{e98b}"
    case conversation = "\u{e98c}"
    case ip = "\u{e98d}"
    case minimize = "\u{e98e}"
    case closeFilled = "\u{e98f}"
    case ipBlock = "\u{e990}"
    case sync = "\u{e991}"
    case errorCircle = "\u{e992}"
    case textEdit = "\u{e993}"
    case twillo = "\u{e994}"
    case currencyDollar = "\u{e995}"
    case shared = "\u{e996}"
    case pushPin = "\u{e997}"
    case pushPin1 = "\u{e998}"
    case pushPinFilled = "\u{e999}"
    case pushPin1Filled = "\u{e99a}"
    case customPrompt = "\u{e99b}"
    case apply = "\u{e99c}"
    case macro = "\u{e99d}"
    case customAnswer = "\u{e99e}"
    case cleanAll = "\u{e99f}"
    case read = "\u{e9a0}"
    case unread = "\u{e9a1}"
    case dollar = "\u{e9a2}"
    case bellFilled = "\u{e9a3}"
    case verifiedTag = "\u{e9a4}"
    case aiStar = "\u{e9a5}"
    case refresh01 = "\u{e9a6}"
    case checkbox01 = "\u{e9a7}"
    case flag01 = "\u{e9a8}"
    case flag01Filled = "\u{e9a9}"
    case `return` = "\u{e9aa}"
    case password = "\u{e9ab}"
    case mailCheck = "\u{e9ac}"
    case notificationOff = "\u{e9ad}"
    case logOut = "\u{e9ae}"
    case numeric1 = "\u{e9af}"
    case chart01 = "\u{e9b0}"
    case table01 = "\u{e9b1}"
    case pivotTable = "\u{e9b2}"
    case doughnutChart = "\u{e9b3}"
    case columns = "\u{e9b4}"
    case lineChart = "\u{e9b5}"
    case replicate = "\u{e9b6}"
    case telegram = "\u{e9b7}"
    case mailReceive = "\u{e9b8}"
    case infoFill = "\u{e9b9}"
    case mailSend = "\u{e9ba}"
    case pyramid = "\u{e9bb}"
    case linkHorizontal = "\u{e9bc}"
    case barChart = "\u{e9bd}"
    case columnChart = "\u{e9be}"
    case stackedBar = "\u{e9bf}"
    case stackedColumn = "\u{e9c0}"
    case ticketGroup = "\u{e9c1}"
    case chatGroup = "\u{e9c2}"
    case manage = "\u{e9c3}"
    case replicate01 = "\u{e9c4}"
    case replicate02 = "\u{e9c5}"
    case insertCode2 = "\u{e9c6}"
    case highlightText = "\u{e9c7}"
    case manageDashboard = "\u{e9c8}"
    case createDashboard = "\u{e9c9}"
    case workflow = "\u{e9ca}"
    case viewReplicate = "\u{e9cb}"
    case referEarn = "\u{e9cc}"
    case chevronDownDouble = "\u{e9cd}"
    case pause = "\u{e9ce}"
    case started = "\u{e9cf}"
    case notStarted = "\u{e9d0}"
    case sortArrow = "\u{e9d1}"
    case microphone = "\u{e9d2}"
    case pause01 = "\u{e9d3}"
    case startRecord = "\u{e9d4}"
    case gupshup = "\u{e9d5}"
    case meta = "\u{e9d6}"
    case ozonetal = "\u{e9d7}"
    case microphoneFilled = "\u{e9d8}"
    case quickStart01 = "\u{e9d9}"
    case internalChat = "\u{e9da}"
    case launch = "\u{e9db}"
    case pauseFill = "\u{e9dc}"
    case aiAgent = "\u{e9dd}"
    case aiAction = "\u{e9de}"
    case customBox = "\u{e9df}"
    case convertDraft = "\u{e9e0}"
    case saveSettings = "\u{e9e1}"
    case sdkFile = "\u{e9e2}"
    
    var unicode: String {
        return rawValue
    }
}

struct AppIcon: View {
    let icon: AppIcons
    var size: CGFloat
    var color: Color

    init(icon: AppIcons, size: CGFloat = 20, color: Color = Color.textTeritiaryColor) {
        self.icon = icon
        self.size = size
        self.color = color
    }

    /// Convenience constructor for app bar icons
    static func appbar(_ icon: AppIcons, size: CGFloat = 24) -> AppIcon {
        return AppIcon(icon: icon, size: size, color: .appBarForegroundColor)
    }

    var body: some View {
        Text(icon.unicode)
            .font(.custom("CustomIcons", size: size))
            .foregroundColor(color)
    }
}

struct AllIconsGridView: View {
    private let columns = [
        GridItem(.flexible()),
        GridItem(.flexible()),
        GridItem(.flexible()),
        GridItem(.flexible())
    ]

    var body: some View {
        ScrollView {
            LazyVGrid(columns: columns, spacing: 16) {
                ForEach(AppIcons.allCases, id: \.self) { icon in
                    VStack {
                        AppIcon(icon: icon)
                            .padding(.bottom, 2)
                        Text(String(describing: icon))
                            .font(.caption)
                            .italic()
                            .bold()
                            .foregroundColor(.textTeritiaryColor)
                            .lineLimit(1)
                            .minimumScaleFactor(0.7)
                    }
                    .padding(4)
                }
            }
            .padding()
        }
    }
}


#Preview {
    ///This is how you should use App Icons
    // AppIcon(icon: .ticket)
    ///You can also specify size and color
    AllIconsGridView()
}
            
